packaging: Declare bundled NPM dependencies in spec file
cockpit-project/starter-kit pull request #634
Opened 2023-04-03 08:05 UTC by martinpitt

See https://bugzilla.redhat.com/show_bug.cgi?id=2180520

----

```
❱❱❱ rpm -q --provides -p cockpit-starter-kit-1-1.fc37.noarch.rpm
bundled(npm(@patternfly/patternfly)) = 4.224.4
bundled(npm(@patternfly/react-core)) = 4.276.8
bundled(npm(react)) = 17.0.2
bundled(npm(react-dom)) = 17.0.2
cockpit-starter-kit = 1-1.fc37
metainfo()
metainfo(org.cockpit-project.starter-kit.metainfo.xml)
```

2023-04-03 08:12 UTC, martinpitt commented
The CI failures are due to the RH internal npm mirror being out of date -- it has version 3.2.0, but not 3.3.0. The latter [was published](https://www.npmjs.com/package/html-tags?activeTab=versions) a day ago. Well, let's firs discuss that with @thoger in bugzilla.

2023-04-03 08:36 UTC, martinpitt commented
Given that we need transitive dependencies, parsing package-lock.json is not trivial (not hard, but it'd require a fully fledged Python script at least), and we most probably want this in dist-git and srpms as well, I think I want to do this at release time instead:
```
❱❱❱ npm ls --omit dev --package-lock-only --depth 10  | grep -Eo '[^[:space:]]+@[^[:space:]]+' | sort -u | sed 's/^/Provides: bundled(npm(/; s/\(.*\)@/\1)) = /'
Provides: bundled(npm(@patternfly/patternfly)) = 4.224.4
Provides: bundled(npm(@patternfly/react-core)) = 4.276.8
Provides: bundled(npm(@patternfly/react-icons)) = 4.93.6
Provides: bundled(npm(@patternfly/react-styles)) = 4.92.6
Provides: bundled(npm(@patternfly/react-tokens)) = 4.94.6
Provides: bundled(npm(attr-accept)) = 1.1.3
Provides: bundled(npm(core-js)) = 2.6.12
Provides: bundled(npm(file-selector)) = 0.1.19
Provides: bundled(npm(focus-trap)) = 6.9.2
Provides: bundled(npm(js-tokens)) = 4.0.0
Provides: bundled(npm(loose-envify)) = 1.4.0
Provides: bundled(npm(object-assign)) = 4.1.1
Provides: bundled(npm(popper.js)) = 1.16.1
Provides: bundled(npm(prop-types-extra)) = 1.1.1
Provides: bundled(npm(prop-types)) = 15.8.1
Provides: bundled(npm(react-dom)) = 17.0.2
Provides: bundled(npm(react-dropzone)) = 9.0.0
Provides: bundled(npm(react-is)) = 16.13.1
Provides: bundled(npm(react)) = 17.0.2
Provides: bundled(npm(scheduler)) = 0.20.2
Provides: bundled(npm(tabbable)) = 5.3.3
Provides: bundled(npm(tippy.js)) = 5.1.2
Provides: bundled(npm(tslib)) = 2.5.0
Provides: bundled(npm(warning)) = 4.0.3
```
I.e. we don't track this in git, but do it at `make dist` time.

2023-04-05 07:48 UTC, marusak requested changes
Nice, thank you! I am not super sure about the `--depth=10` part. You can use `--all` instead of `--depth` but that seems to do more than just showing full depth, but you can do `--depth=Infinity` which seems more correct.

2023-04-05 07:52 UTC, martinpitt commented
@marusak : Cool, thanks! Changed. (It would help if `npm ls --help` pointed that out, and the advertised `npm help ls` would actually work..)

2023-04-05 07:56 UTC, marusak approved these changes
Thanks!

2023-04-05 08:17 UTC, merged