build.js: use argparse instead of env variables
cockpit-project/starter-kit pull request #679
Opened 2023-07-25 09:35 UTC by tomasmatus

Replaces env variables with flags to use rsync, disable linting and enable watch mode.

2023-07-25 13:06 UTC, martinpitt requested changes
Thanks! Can you please update README accordingly?

2023-07-25 13:08 UTC, tomasmatus commented
> Thanks! Can you please update README accordingly?

ah yes, will do!

2023-07-25 13:11 UTC, martinpitt commented
I'm not sure how many people actually use the env vars. `LINT=0 make watch` would have been a sensible invocation, but I'm okay with letting this go.

2023-07-25 13:14 UTC, tomasmatus commented
Maybe then I can keep both options possible? Env variables and build.js flags

2023-07-25 13:27 UTC, martinpitt commented
Yes, but maybe let's see if anyone actually complains :grin:

2023-07-25 13:36 UTC, jelly requested changes
This line still uses `ESLINT` needs updating https://github.com/cockpit-project/starter-kit/blob/3d75eb66d7559c5cf2f761f061147382af2f72d0/packaging/cockpit-starter-kit.spec.in#L35

2023-07-25 13:36 UTC, jelly commented on build.js
> -const lint = process.env.LINT ? (process.env.LINT !== '0') : (watchMode || !production);
I thought we supported this still in `cockpit` but just checked and it seems not!.

2023-07-25 13:36 UTC, jelly commented on build.js
> -const lint = process.env.LINT ? (process.env.LINT !== '0') : (watchMode || !production);
But shouldn't we keep `LINT` to be flexible in Makefile's @martinpitt what do you think?

2023-07-26 08:52 UTC, martinpitt requested changes
Thanks!

2023-07-26 08:52 UTC, martinpitt commented on README.md
> +    $ ./build.js -e -s
Let's do this as `-es` for short, as humans will actually type this.

2023-07-26 08:52 UTC, martinpitt commented on README.md
> +    $ LINT=0 make
Not a strong opinion, but let's drop this. Cockpit doesn't support it either, and it's nicer to have *one* way of doing things.

2023-07-26 08:52 UTC, martinpitt commented on build.js
> +parser.add_argument('-s', '--no-stylelint', { action: 'store_true', help: "Disable stylelint linting", default: process.env.LINT ? process.env.LINT === '0' : production });
Very long lines, and DRY. Please keep it outside as a const (like in old line 23) and rename it to `lint_default`.

2023-07-26 08:52 UTC, martinpitt commented on packaging/cockpit-starter-kit.spec.in
> +LINT=0 NODE_ENV=production make
Ah, this is a good justification for keeping `$LINT`.

2023-07-26 09:17 UTC, martinpitt approved these changes
Very nice, thank you! Can you please also apply this to all our other projects, so that we don't keep getting confused?

2023-07-26 09:17 UTC, martinpitt commented
@jelly you still have a -1 finger on this, can you PTAL?

2023-07-26 09:18 UTC, tomasmatus commented
> Very nice, thank you! Can you please also apply this to all our other projects, so that we don't keep getting confused?

Yes, I will do that once this is merged

2023-07-26 11:26 UTC, jelly approved these changes

2023-07-26 11:38 UTC, merged

2023-07-26 19:47 UTC, jelly commented
Nice, now podman/machines can have it as well \o/